### ISSUE TITLE
Online generate dataset issues

### ISSUE THREAD

**Issue by Tony-Hou** [Megvii-BaseDetection/BEVDepth#100]
BEVDepth/bevdepth/datasets/nusc_det_dataset.py", line 296, in _get_sample_indices
    [ann_info['category_name'] for ann_info in info['ann_infos']])
TypeError: string indices must be integers

**Comment by yinchimaoliang** [comment]
If I run the cbgs exps, it works fine, can you be more specific?

**Comment by sinsin1998** [comment]
> 
I got the same error, have you solved this problem?
