### ISSUE TITLE
Convnext or Vovnet???

### ISSUE THREAD

**Issue by pummi823** [Megvii-BaseDetection/BEVDepth#109]
Dear author , I observe that you say the leaderboard result is from the backbone of Convnext on 2022.8.4, but you also say it is Vovnet on 2022.9.3。。。 So which one is it?

**Comment by pummi823** [comment]
> I haven't submitted result in neither 2022.8.4 nor 2022.9.3, I am confused of what you are referring to.

Hi, I mean, in #20 (8.4) and in #53 (9.3) you have answer other people of the different backbone

**Comment by yinchimaoliang** [comment]
We have submitted two results on the nuscenes leaderboard. Two different types of backones are applied for each submission. Please refer to nuscenes leaderboard.

**Comment by pummi823** [comment]
> We have submitted two results on the nuscenes leaderboard. Two different types of backones are applied for each submission. Please refer to nuscenes leaderboard.

Oh! Thanks so much~~ could you please when the input size is (640, 1600), what the final_dim and resize_lim shold be change to? Especially resize_lim,  I really can not find the law ( T . T)

**Comment by yinchimaoliang** [comment]
The 'resize_lim" I use is (0.94, 1.25).

**Comment by pummi823** [comment]
> The 'resize_lim" I use is (0.94, 1.25).

OK!! Thank you so much!
