### ISSUE TITLE
'SECONDFPN is not in the models registry'

### ISSUE THREAD

**Issue by shijinghuihub** [Megvii-BaseDetection/BEVDepth#11]
line 76 of bev_depth_head.py （self.neck = build_neck(bev_neck_conf) ）： 'SECONDFPN is not in the model registry'

**Comment by rockywind** [comment]
I met the same error!
``'
    raise KeyError(
KeyError: 'SECONDFPN is not in the models registry'
``'

**Comment by yinchimaoliang** [comment]
Please check if you have installed the right version of `mmdet3d` first.
