### ISSUE TITLE
评测报错

### ISSUE THREAD

**Issue by sunbin1357** [Megvii-BaseDetection/BEVDepth#111]
按照readme训练是可以正常训练的。目前进行评测的时候运行以下命令
`python bevdepth/exps/mv/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da_ema.py   --ckpt_path outputs/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da_ema/lightning_logs/version_2/22.pth  -e -b 8 --gpus 1`

会报错
![image](https://user-images.githubusercontent.com/47880903/204542867-034a8228-4d74-4b9f-b7b3-cf12a1352ab7.png)

这个问题有遇到过吗

**Comment by yinchimaoliang** [comment]
请检查是否是validation的info.pkl没有加载上

**Comment by Ignite616** [comment]
您好，请问按照readme训练时，python [EXP_PATH] --amp_backend native -b 8 --gpus 8；这条命令中的EXP_PATH应该是哪个py文件的路径呢？

**Comment by yinchimaoliang** [comment]
您好，和训练的exp的路径是一致的
