### ISSUE TITLE
Config issue about MatrixVT

### ISSUE THREAD

**Issue by TmacTmac1992** [Megvii-BaseDetection/BEVDepth#129]
Hi, 
When I train or eval matrixvt, I got an error: 

TypeError: __init__() missing 2 required positional arguments: 'backbone_conf' and 'head_conf'

**Comment by ZRandomize** [comment]
hi，this is due to model initialization. change [this line](https://github.com/Megvii-BaseDetection/BEVDepth/blob/664fcb031040d2884e849f527b64808b6a62ca09/bevdepth/models/matrixvt_det.py#L16) into "super(BaseBEVDepth, self).__init__()" will help. We'll fix this bug soon, thanks for reporting

**Comment by TmacTmac1992** [comment]
Thanks for your quick reply!
