### ISSUE TITLE
depth supervision good for ate and map but not for the others

### ISSUE THREAD

**Issue by ruolinsss** [Megvii-BaseDetection/BEVDepth#134]
Dear author, when I am playing with bevdepth with nuscenes and my own dataset, I found depth loss is quite good for predicting the center location of objects but not good for their dimension and orientations, e.g. removing depth loss from 15th epoch could achieving better AOE and ASE but worse MAP and ATE, and resulting in similar NDS. Could you perhaps give some assumptions for this problem? Thanks!

**Comment by yinchimaoliang** [comment]
In my experimence, dimension and orientations need more time to converge. Perhaps removing depth loss makes it focus more on these two tasks, therefore mAP and mATE is relatively low.

**Comment by ruolinsss** [comment]
Thanks, I will try to train more iterations!
