### ISSUE TITLE
To use bfloat16 with native amp you must install torch greater or equal to 1.10

### ISSUE THREAD

**Issue by shijinghuihub** [Megvii-BaseDetection/BEVDepth#14]
My version is :
```
python 3.7
cuda 11.1
torch==1.9.0+cu111
torchvision==0.10.0+cu111 
pytorch-lightning: 1.6.5 
mmcv-full 1.5.0
mmdet 2.25.0
mmdet3d 0.18.0
mmsegmentation 0.26.0
```

 `To use bfloat16 with native amp you must install torch greater or equal to 1.10.` in `trainer = pl.Trainer.from_argparse_args(args, callbacks=[ema_callback])`

could you tell us the exact version？

**Comment by yinchimaoliang** [comment]
Hello, The precision mode we use for amp is float16 rather than bfloat16, it works fine on torch1.9.0. If you'd like to use bfloat16, you can update your pytorch version to 1.10 and try it.

**Comment by Like2021** [comment]
+1

my version is:
`python 3.7
cuda 11.3
torch==1.9.0+cu111
torchvision==0.10.0+cu111 
pytorch-lightning: 1.6.0 
mmcv-full 1.7.0
mmdet 2.25.3
mmdet3d 1.0.0rc5
mmsegmentation 0.29.1`

i used `bev_depth_fusion_lss_r50_256x704_128x128_24e.py`
and set precision=16, but still got this error.
eg:
`parser.set_defaults(profiler='simple',
                    deterministic=False,
                    max_epochs=24,
                    accelerator='ddp',
                    num_sanity_val_steps=0,
                    gradient_clip_val=5,
                    limit_val_batches=0,
                    enable_checkpointing=True,
                    precision=16,
                    default_root_dir=os.path.join('./outputs/', exp_name))`

i found that when building the model "precision" of the args still is 16, 
![image](https://user-images.githubusercontent.com/95627417/204117257-a08ce99d-5010-467e-91ac-a35af3c3f957.png)

but after building the model, like this:
![image](https://user-images.githubusercontent.com/95627417/204117276-204fd71e-810d-4355-a152-5ed69c729ae5.png)

then `trainer = pl.Trainer.from_argparse_args(args)` will return i used "bf16", like this:
![image](https://user-images.githubusercontent.com/95627417/204117339-e655b0e5-0457-459a-9c0f-27164faa4e84.png)

Do you have any good suggestions besides modifying the version of torch?

Obviously, I didn't change the precision mode.
