### ISSUE TITLE
BEV grid resolution

### ISSUE THREAD

**Issue by tjqansthd** [Megvii-BaseDetection/BEVDepth#146]
Hi! thanks for the great work.

If I want to train BEVDepth using 256x256 BEV grid resolution, How should I modifiy the setting?
Do I just have to change
```
1. 'voxel_size=[0.2, 0.2, 8]' to 'voxel_size=[0.1, 0.1, 8]' 
2. 'x_bound: [-51.2, 51.2, 0.8]' to 'x_bound: [-51.2, 51.2, 0.4]'
3. 'y_bound: [-51.2, 51.2, 0.8]' to 'y_bound: [-51.2, 51.2, 0.4]'
```
in base_exp.py,
or is there anything else to consider?

Thanks.

**Comment by yinchimaoliang** [comment]
Hi there, you also need to consider `out_size_factor`.

**Comment by tjqansthd** [comment]
Oh, I see. It is used in calculating ```feature_map_size```.
Thank you!

**Comment by yukaizhou** [comment]
> Oh, I see. It is used in calculating `feature_map_size`. Thank you!

Hi there。After following this modification, is your result normal? According to your description, the same modification was made in the original code. specifically is
`backbone_conf：
1，x_bound: [-51.2, 51.2, 0.8]-->:[-51.2, 51.2, 0.4];
2, y_bound: [-51.2, 51.2, 0.8]-->:[-51.2, 51.2, 0.4];
bbox_coder：
1， out_size_factor=4 --> 2,
2, voxel_size=[0.2, 0.2, 8] --> [0.1, 0.1, 8];
train_cfg：
1， out_size_factor=4 --> 2,
2, voxel_size=[0.2, 0.2, 8] --> [0.1, 0.1, 8];
test_cfg：
1， out_size_factor=4 --> 2,
2, voxel_size=[0.2, 0.2, 8] --> [0.1, 0.1, 8];`
Other than that there are no changes.
But there is no result at all, that is, mAP=0.

**Comment by tjqansthd** [comment]
> > Oh, I see. It is used in calculating `feature_map_size`. Thank you!
> 
> Hi there。After following this modification, is your result normal? According to your description, the same modification was made in the original code. specifically is `backbone_conf： 1，x_bound: [-51.2, 51.2, 0.8]-->:[-51.2, 51.2, 0.4]; 2, y_bound: [-51.2, 51.2, 0.8]-->:[-51.2, 51.2, 0.4]; bbox_coder： 1， out_size_factor=4 --> 2, 2, voxel_size=[0.2, 0.2, 8] --> [0.1, 0.1, 8]; train_cfg： 1， out_size_factor=4 --> 2, 2, voxel_size=[0.2, 0.2, 8] --> [0.1, 0.1, 8]; test_cfg： 1， out_size_factor=4 --> 2, 2, voxel_size=[0.2, 0.2, 8] --> [0.1, 0.1, 8];` Other than that there are no changes. But there is no result at all, that is, mAP=0.

Hi, if you change `voxel_size=[0.2, 0.2, 8]-->[0.1, 0.1, 8]` and `grid_size=[512, 512, 1]-->[1024, 1024,1]` in train_cfg, test_cfg, bbox_coder, you don't need to change `out_size_factor=4 --> 2`.
