### ISSUE TITLE
Is there any way to recreate the results on the nuscenes detection leaderboard? I tried training the model but only reached an NDS of around 0.45.

### ISSUE THREAD

**Issue by Bluffish** [Megvii-BaseDetection/BEVDepth#16]

**Comment by yinchimaoliang** [comment]
Hello! There are several things to do, increasing the resolution of the input images, using more powerful backone and using dcn centerhead, etc.

**Comment by Bluffish** [comment]
Hello, thanks for the reply! Can you tell me the differences between each of the exp files? I have trained the one ending with 24e_2key.py so far.

**Comment by yinchimaoliang** [comment]
The name is constructed following the rule of [model]_[backbone]_[input_resolution]_[bev_resolution]_[num_epoch]_[cbgs]_[num_sweep]_[depth_aggregation].
