### ISSUE TITLE
BEVDepth perform very bad when training with batch size 1!

### ISSUE THREAD

**Issue by cskkxjk** [Megvii-BaseDetection/BEVDepth#164]
Hi! I'm currently training the bevdepth models with different batch size.
I used 1,2,4,8 GPUs with batch size=1, 2, 4.
All the models trained with batch size=1 seems to perform bad on nuScenes val set (0\~3mAP).
All the models trained with batch size != 1 perform reasonable (20\~30mAP).

can you give me some advices about how to change the config to make it work when batch size=1?

**Comment by hutchinsonian** [comment]
When batch size=1, what is your GPU memory usage？

**Comment by cskkxjk** [comment]
> When batch size=1, what is your GPU memory usage？

the GPU memory is about 6G when batch size is 1, the experiment config is ```bev_depth_lss_r50_256x704_128x128_24e.py``` modified from ```bev_depth_lss_r50_256x704_128x128_24e_ema.py```
