### ISSUE TITLE
The inference results of the MatrixVT model do not match the ground truth.

### ISSUE THREAD

**Issue by wuhandashuaibi** [Megvii-BaseDetection/BEVDepth#195]
The model of MatrixVT with this weight [https://github.com/ZRandomize/MatrixVT/releases/tag/weights](url)
exp name: matrixvt_bev_depth_lss_r50_256x704_128x128_24e_ema_cbgs
visualize the predict result at here:
![plot_pre](https://github.com/Megvii-BaseDetection/BEVDepth/assets/51684492/e5092eef-c1a3-4836-b287-e3740327d239)
visualize the gt at here:
![plot_gt](https://github.com/Megvii-BaseDetection/BEVDepth/assets/51684492/d7d2be9f-8a50-4a92-a27c-d336e4b1e922)
Is this correct?

**Comment by heshameraqi** [comment]
The bounding boxes results look shifted by some threshold in the camera images. To avoid this comment the line:
`box3d[2] += 0.5 * box3d[5]` in scripts/visualize_nusc.py line 196. The result will get corrected from the first image below to the second one:

<img width="2400" height="800" alt="Image" src="https://github.com/user-attachments/assets/d0f90ced-3858-4071-86cb-5405783552f1" />

<img width="2400" height="800" alt="Image" src="https://github.com/user-attachments/assets/2c01d8ef-a818-428d-a24d-d292893c041d" />
