### ISSUE TITLE
Training Log

### ISSUE THREAD

**Issue by Divadi** [Megvii-BaseDetection/BEVDepth#22]
Hi, would it be possible to have the training log?

**Comment by yinchimaoliang** [comment]
The training log is saved while training in the tensorboard format.

**Comment by Divadi** [comment]
Ah, I understand. I had wanted to check some training details (if a learning rate scheduler is used, convergence rate, etc). Also, I was wondering why you decided to use EMA; is there a significant difference?

**Comment by yinchimaoliang** [comment]
When EMA is applied, lr stays the same in the shole training process. In the early stage of our development, EMA is able to promote NDS about 1%, when BEVDepth is stable, no ablation study is conducted.

**Comment by zhaozp15** [comment]
@yinchimaoliang I also wonder if a learning rate scheduler is used.

**Comment by Divadi** [comment]
From what I can tell during training, the learning rate is constant without warmup either.

**Comment by zhaozp15** [comment]
Thank you so much for your reply!
