### ISSUE TITLE
Weight Decay

### ISSUE THREAD

**Issue by Divadi** [Megvii-BaseDetection/BEVDepth#24]
I saw that the CBGS experiment config was updated to have 1e-2 weight decay - should the non-CBGS config and the single-frame config also have 1e-2 instead of 1e-7?
https://github.com/Megvii-BaseDetection/BEVDepth/blob/72116c367a0fb6ffed61e72fd71cefb157cb0e45/exps/bev_depth_lss_r50_256x704_128x128_24e.py#L368-L373

**Comment by yinchimaoliang** [comment]
The `weight_decay` was set to 1e-7 in the beginning. But when we conduct experiments on the cbgs exps, it may cause loss expansion during training, so we change it to 1e-2.

**Comment by Divadi** [comment]
Thank you for the clarification!

**Comment by zeyuwang615** [comment]
> The `weight_decay` was set to 1e-7 in the beginning. But when we conduct experiments on the cbgs exps, it may cause loss expansion during training, so we change it to 1e-2.

Only the weight_decay in bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da_ema.py is set to 1e-2. The weight_decay in bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da.py is still 1e-7. I wonder what is the relation between weight_decay and ema?
