### ISSUE TITLE
Implementation details of convnext model

### ISSUE THREAD

**Issue by SuperHenry2333** [Megvii-BaseDetection/BEVDepth#25]
Dear authors,
Thank you for your excellent work! I have some questions about the convnext model. You provided very helpful information in issue #20 and I have a few more questions about this.

1. Do you only use convnext as image backbone and keep the bev_backbone unchanged or do you also change the bev_backbone?
2. When I changed bev resolution to 256x256, I found I need to change train_cfg['out_size_factor'] from 4 to 2 so that the predicted heatmap has the same resolution as the gt heatmap. Is my change correct? If yes, do I also need to change bbox_coder['out_size_factor'] and test_cfg['out_size_factor'] to 2?

Thank you again for your great contribution to this area!

**Comment by yinchimaoliang** [comment]
Hi, @SuperHenry2333 
1. Yes, we only change image backbone and bev_backbone stays the same.
2. If you'd like to change bev resolution, `x_bound`, `y_bound`, `out_size_factor` in `bbox_coder`, `train_cfg` and `test_cfg` should all be changed.

**Comment by SuperHenry2333** [comment]
Thank you very much for quick reply

**Comment by pummi823** [comment]
Hi! I want to know where you change the para of bev resolution to 256x256??? I can not found T T. Best wishes!!
