### ISSUE TITLE
 Question About randomly sampling time intervals in previous frames

### ISSUE THREAD

**Issue by Serenade-ajp** [Megvii-BaseDetection/BEVDepth#27]
Hello, thanks for sharing your code.
I see that you conduct data augmentation by randomly sampling time intervals in previous frames.
I wonder whether you can explain some details about it, like the longest time interval allowed, sample key frames or sweeps, and how to set the sampling interval when doing inference

**Comment by swtju14** [comment]
Hi, @Serenade-ajp. Following BEVDet4D , we randomly sample a frame as previous frame from [3T; 27T] during training,
and sample the frame at 15T during inference. T(≈0.083) is the time interval between two sweep
frames.

**Comment by Serenade-ajp** [comment]
> Hi, @Serenade-ajp. Following BEVDet4D , we randomly sample a frame as previous frame from [3T; 27T] during training, and sample the frame at 15T during inference. T(≈0.083) is the time interval between two sweep frames.

Thanks for your reply, it's clear for me now!
