### ISSUE TITLE
About the training script

### ISSUE THREAD

**Issue by chaoqunwangcs** [Megvii-BaseDetection/BEVDepth#29]
Thanks to the great job!
However, I retrained the model with config: "bev_depth_lss_r50_256x704_128x128_24e.py' absolutely follow the Readme, the depth loss is about 8 and the detection loss is about 6. When is test with the latest checkpoint, the NDS is only about 35% and the mAP is about 31%. Is it normal? or are there any other problems?

**Comment by Joker316701882** [comment]
@chaoqunwangcs It is normal. Since you are using the config for training on the single frame setting. The performance on single frame is normally inferior to multi-frame setting, especially on mAVE and NDS. Please refer to our paper for more details.
