### ISSUE TITLE
ablation study about ASPP module

### ISSUE THREAD

**Issue by HuangJunJie2017** [Megvii-BaseDetection/BEVDepth#30]
hi, I found that the implementation of this repo uses the ASPP module
I am curious about the ablation study of this module which is not in the manuscript~
Does it has been considered in the ablation study of Depth Correction in Table 1?

**Comment by yinchimaoliang** [comment]
Hi! Depth Correction is used as a whole module for ablation study. The experiment of using ASPP separately has not  beenconducted

**Comment by HuangJunJie2017** [comment]
thanks I see
