### ISSUE TITLE
Could help indicate clearly how to install pytorch? which verison?

### ISSUE THREAD

**Issue by Barnonewdm** [Megvii-BaseDetection/BEVDepth#33]
Just struggling to install the pytorch, torchvision, cudatoolkit, and so on. PLEASE help indicate the version.

**Comment by yinchimaoliang** [comment]
The version of pytorch is v1.9.0, please to `README`

**Comment by Barnonewdm** [comment]
In case anyone comes across the issue, here is a workable solution:

`pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html`

`pip install mmcv=1.6.0`
