### ISSUE TITLE
bug: calculate camera param in augmentation

### ISSUE THREAD

**Issue by sephyli** [Megvii-BaseDetection/BEVDepth#34]
https://github.com/Megvii-BaseDetection/BEVDepth/blob/a030aae76f5c74830f0707db4b10136adf3bcaea/dataset/nusc_mv_det_dataset.py#L75
Maybe should be changed to `ida_mat[:2, 2] = ida_tran`.

**Comment by sephyli** [comment]
In theory, there is no doubt that `ida_tran` should be placed in `[:2, 2]`, but I also used visualization to verify, and the visualization results of the modified version are in line with expectations.

Raw:
![test0](https://user-images.githubusercontent.com/39691156/185543368-a2fd1340-ee1b-478c-a7a8-50d707243c90.jpg)
Wrong:
![test1](https://user-images.githubusercontent.com/39691156/185543216-7c8e9487-f7dc-4534-b883-2bde99a88f81.jpg)
Right:
![test2](https://user-images.githubusercontent.com/39691156/185543292-b646392f-2f67-4f7a-9fdc-d86c191cd8bc.jpg)

**Comment by yinchimaoliang** [comment]
The matrix we use is 4x4, that's why we use `ida_mat[:2, 3] = ida_tran`.

**Comment by sephyli** [comment]
I use 4x4 matrix too. Here:
The final `lidar2img = ida_mat @ cam_in @ cam_out`
And the points in visualization is calculed by `pts2d = pts4d @ lidar2img.T` and divided by pts2d[:, 2] where pts2d[:, 2] > 0, which pts4d is (N, 4) in format (x, y, z, 1).
Is there anything wrong?

**Comment by zyc573823770** [comment]
I meet the same question and it works to change `ida_mat[:2, 2] = ida_tran`.
