### ISSUE TITLE
loss explodes in last epoches

### ISSUE THREAD

**Issue by Tony-Hou** [Megvii-BaseDetection/BEVDepth#36]
I use the  bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da.py default  config  to reproduce  the reuslt on the 8  A100 80G  GPUS . Train loss explodes in last epoches, the follow picture show the details:
![Screenshot from 2022-08-22 10-22-33](https://user-images.githubusercontent.com/26059901/185831325-b39053a9-7d29-4082-b6a1-56f8491ed518.png)

[hparams.txt](https://github.com/Megvii-BaseDetection/BEVDepth/files/9390996/hparams.txt)

Another a  experiments have the same problems on 4 V100 32G gpus with set 40 epoches  to train.
python3 exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da.py --amp_backend native -b 8 --gpus 4
 
![Screenshot from 2022-08-22 10-27-48](https://user-images.githubusercontent.com/26059901/185831902-075a21d0-ba7c-4872-8326-3979b10831dd.png)

[hparams_v100.txt](https://github.com/Megvii-BaseDetection/BEVDepth/files/9391012/hparams_v100.txt)

**Comment by yinchimaoliang** [comment]
Hi! @Tony-Hou You can change the `weight_decay` to a greater value to see if this can be fixed.

**Comment by ytwanghaoyu** [comment]
@Tony-Hou I met the same problem. I wonder how you solved this problem?
