### ISSUE TITLE
Voxel Pooling Cuda code possible mistake at ranking

### ISSUE THREAD

**Issue by cmtrhn** [Megvii-BaseDetection/BEVDepth#51]
In voxel pooling there is a ranking system that separates all voxel locations from each other. It is calculated as follows in python code:

```python
ranks = geom_feats[:, 0] * (self.nx[1] * self.nx[2] * B) \
                + geom_feats[:, 1] * (self.nx[2] * B) \
                + geom_feats[:, 2] * B \
                + geom_feats[:, 3]
```

feat [0] has z axis, [1] has y axis and [2] has x axis information [3] contains batch number. Variable nx contains limits on x,y,z axes.

The cuda code for accelerated voxel pooling has a missing multiplication. This might be a mistake, or I might be missing something:

```cuda
atomicAdd(
          &output_features[(batch_idx * num_voxel_y * num_voxel_x + y * num_voxel_x + x) * num_channels + channel_idx],
          input_features[pt_idx * num_channels + channel_idx]);
```

z coordinate is only 1 therefore it is encoded with (batch * max_x * max_y) but then y coordinate and x coordinate is not multiplied with batch index. And there is no addition of batch index as is in the case of python code.

Is this a mistake?

Thanks,
Cem

**Comment by yinchimaoliang** [comment]
Thanks for your comment. However, I don't think it is a mistake, the idx are calculated correctly, otherwise, it is unable to pass the unittest. There may be something you are missing.

**Comment by cmtrhn** [comment]
Ok, thank you very much.
