### ISSUE TITLE
Is it correct to replace resnet50 with regnetx_1.6gf as  backbone?

### ISSUE THREAD

**Issue by Tony-Hou** [Megvii-BaseDetection/BEVDepth#55]
`'img_backbone_conf':
    dict(
        type='RegNet',
        arch='regnetx_1.6gf',
        frozen_stages=0,
        out_indices=[0, 1, 2, 3],
        norm_eval=False,
        init_cfg=dict(type='Pretrained', checkpoint='open-mmlab://regnetx_1.6gf'),
    ),
    'img_neck_conf':
    dict(
        type='SECONDFPN',
        in_channels=[72, 168, 408, 912],   # [256, 512, 1024, 2048]
        upsample_strides=[0.25, 0.5, 1, 2],
        out_channels=[128, 128, 128, 128],
    ),`

**Comment by yinchimaoliang** [comment]
It looks good to me.
