### ISSUE TITLE
How to train model of  largger scale as  input size?

### ISSUE THREAD

**Issue by Tony-Hou** [Megvii-BaseDetection/BEVDepth#59]
I  changed   final_dim value  of  the bev_depth_lss_r50_256x704_128x128_24e.py  code:
`final_dim = (896, 1600)`

The train loss is  normal, but the metrices is very low.   How to train model of  largger scale as  input size?

**Comment by yinchimaoliang** [comment]
You should change `scale_factor` in `ida` accordingly.

**Comment by Tony-Hou** [comment]
> You should change `scale_factor` in `ida` accordingly.
`ida_aug_conf = {
    'resize_lim': (0.386, 0.55),
    'final_dim':
    final_dim,
    'rot_lim': (-5.4, 5.4),
    'H':
    H,
    'W':
    W,
    'rand_flip':
    True,
    'bot_pct_lim': (0.0, 0.0),
    'cams': [
        'CAM_FRONT_LEFT', 'CAM_FRONT', 'CAM_FRONT_RIGHT', 'CAM_BACK_LEFT',
        'CAM_BACK', 'CAM_BACK_RIGHT'
    ],
    'Ncams':
    6,
}`
The final_dim map is assigned final_dim variable ,   Is scale_factor you mean resize_lim ?

**Comment by yinchimaoliang** [comment]
Yes, I mean `resize_lim`.

**Comment by Tony-Hou** [comment]
> Yes, I mean `resize_lim`.
If input size is changed to  896x1600,  How to set the resize_lim value corresponding?

**Comment by yinchimaoliang** [comment]
You may change to [0.95, 1.25].

**Comment by Tony-Hou** [comment]
> You may change to [0.95, 1.25].
Ok, I will try it.  What is the reasons  that to set  [0.95, 1.25] ? It is an experimental parameter?
