### ISSUE TITLE
Problem of EMA

### ISSUE THREAD

**Issue by MalignusCN** [Megvii-BaseDetection/BEVDepth#70]
Hi, I've got some questions about the EMA. In the repo of our git, the "exps/bev_depth_lss_r50_256x704_128x128_24e_ema.py" & "exps/bev_depth_lss_r50_256x704_128x128_24e_ema.py" were not used in  "exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da_ema.py". The "exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da_ema.py" directly use the BEVDepthLightningModel from "exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da". 

I wanna know that if I would like to use the EMA settings, which .py files I should executed. Are there any settings need to modify? ~ Thank you so much.

您好~ 我想请问一下关于EMA的用法问题。我发现在我们的git仓库中，"exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da_ema.py"在使用的时候是没有使用另外两个***_ema.py文件的。想问一下如果想要用我们的EMA来进行训练，是直接执行对应的"exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da_ema.py"就可以吗？是否需要将"exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da.py"的BEVDepthLightningModel从***_2key.py引入，改为从***_2key_ema.py中引入呢？感谢感谢

**Comment by yinchimaoliang** [comment]
You can run `bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da_ema.py` directly.
