### ISSUE TITLE
ConvNext checkpoint

### ISSUE THREAD

**Issue by DianCh** [Megvii-BaseDetection/BEVDepth#79]
Hi! Thank you for releasing this great work. May I ask in you NuScenes leaderboard reasult `BEVDepth-pure`, which checkpoint of your convnext backbone is used (there are many options on the [official convnext page](https://github.com/facebookresearch/ConvNeXt))? Did you pre-train the convnext on nuscenes?

Thank you!

**Comment by pummi823** [comment]
++++++++++++++++1

**Comment by swtju14** [comment]
Hi, @DianCh. BEVDepth-pure extends the BEVDepth by using ConvNeXt-base as backbone. The model we used is pre-trained on ImageNet-1k from [mmclassification convneXt](https://github.com/open-mmlab/mmclassification/tree/master/configs/convnext). We did not pre-train on nuscenes, I hope you can try.

**Comment by Francis777** [comment]
Thanks for the pointer @swtju14! For future reference, to use pretrained ConvNeXt-base as image backbone you can modify https://github.com/Megvii-BaseDetection/BEVDepth/blob/7ff5fab49d24c682acfb3144d9a55cbf2fe84f07/bevdepth/exps/nuscenes/base_exp.py#L39 to the following:
```
dict(
    type="ConvNeXt",
    arch="base",
    out_indices=[0, 1, 2, 3],
    drop_path_rate=0.5,
    gap_before_final_norm=False,
    init_cfg=dict(
        type="Pretrained",
        checkpoint="https://download.openmmlab.com/mmclassification/v0/convnext/convnext-base_3rdparty_32xb128-noema_in1k_20220222-dba4f95f.pth",
    ),
)
``` 
Then running `forward` of this backbone will give you image features at 4 scales with (128, 256, 512, 1024) channels. 
Note that this won't work out of the box in the current repo, you'd need to install `mmclassification`, `mmengine` and upgrade `mmdetection`,  `mmcv` to their rc versions to make sure every library is compatible with each other.

**Comment by DianCh** [comment]
Thank you very much for the references! I'm closing this issue.
