### ISSUE TITLE
Sweep idx

### ISSUE THREAD

**Issue by Divadi** [Megvii-BaseDetection/BEVDepth#8]
Hello, thank you for open-sourcing your code.

For the released model, it seems like you used a previous sweep aggregation. I can't seem to track where the sweep_idxes and num_sweeps are specified; they just seem to default to none here:
https://github.com/Megvii-BaseDetection/BEVDepth/blob/0f55c61cc581a75ca29142f4025a4c870133d3af/exps/bev_depth_lss_r50_256x704_128x128_24e.py#L222-L223
which doesn't seem to be overwritten here 
https://github.com/Megvii-BaseDetection/BEVDepth/blob/0f55c61cc581a75ca29142f4025a4c870133d3af/exps/bev_depth_lss_r50_256x704_128x128_24e_2key.py

Should some command-line parameters be specified?

Thank you!

**Comment by yinchimaoliang** [comment]
Hello, we support two kinds of previous frames' patterns.
One pattern is using previous keyframes, as demonstrated in `https://github.com/Megvii-BaseDetection/BEVDepth/blob/main/exps/bev_depth_lss_r50_256x704_128x128_24e_2key.py#L37`, another is using previous sweep frames as you mentioned. If you'd like to use the second pattern, you can overwrite `sweep_idxes` in your exps. More exp settings will be provided in the future.

**Comment by Divadi** [comment]
Ah I missed that! Thank you for your clarification.
