### ISSUE TITLE
AttributeError: 'BEVDepthLightningModel' object has no attribute 'module'

### ISSUE THREAD

**Issue by FANG-MING** [Megvii-BaseDetection/BEVDepth#80]
```AttributeError: 'BEVDepthLightningModel' object has no attribute 'module'```
```pytorch==1.18.1```
```python==3.6.9```
```lighting_torch==1.5.10```

**Comment by yinchimaoliang** [comment]
Please pytorch-lightning.

**Comment by yinchimaoliang** [comment]
Please update pytorch-lightning to 1.6.0.
