### ISSUE TITLE
I can't find the BEV feature align code in the different timestamps. Can you show me the location of BEV feature alignment?

### ISSUE THREAD

**Issue by rockywind** [Megvii-BaseDetection/BEVDepth#85]
Hi,
I can't find the BEV feature align code in the different timestamps. Can you show me the location of BEV feature alignment?

**Comment by yinchimaoliang** [comment]
The process of alignment is not applied on the bev feature, it is aligned on the coordinates of the pseudo lidar points.

**Comment by rockywind** [comment]
Thanks!
