### ISSUE TITLE
About nuScenes train set used for ablation study

### ISSUE THREAD

**Issue by thom966** [Megvii-BaseDetection/BEVDepth#87]
Hello, thank you for your great work.
I wonder whether the model for the ablation study trained with nuScenes full train set or some portion of dataset.
I am asking this question because the performance of the last row in Table 1 has some performance gap between Table 4.
![image](https://user-images.githubusercontent.com/84850569/196905540-be339997-9a83-4d8f-889e-1bf1db8502ff.png)

Thank you for your reply.

**Comment by yinchimaoliang** [comment]
The experiment in Table 4 uses CBGS, multi-frame and depth aggregation.
