### ISSUE TITLE
depth ground truth

### ISSUE THREAD

**Issue by Orange-rightperson** [Megvii-BaseDetection/BEVDepth#88]
I see gen_depth_gt.py does not exist, is that mean we do not need depth groundtruth? and we do not need depth  estimation?

**Comment by yinchimaoliang** [comment]
Depth gt is generated online now.

**Comment by Orange-rightperson** [comment]
does it mean it has been generated when I train?

**Comment by yinchimaoliang** [comment]
Yes, it is.

**Comment by Orange-rightperson** [comment]
E，could you please tell me how it works?

**Comment by yinchimaoliang** [comment]
During training, lidar points are loaded and transformed to depth gt for supervision.

**Comment by Orange-rightperson** [comment]
where are the codes that transformed lidar points  to depth  located?

**Comment by Orange-rightperson** [comment]
I find it, thankyou

**Comment by YuhanZhou521** [comment]
> where are the codes that transformed lidar points to depth located?

Can you tell me where this code is from? I can't find it either.

**Comment by naivezzc** [comment]
> > where are the codes that transformed lidar points to depth located?
> 
> Can you tell me where this code is from? I can't find it either.

You can find it from BEVDepth/bevdepth/datasets/nusc_det_dataset.py line 107
