### ISSUE TITLE
bug report.  gen_info.py

### ISSUE THREAD

**Issue by XinchaoGou** [Megvii-BaseDetection/BEVDepth#89]
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/35408641/197097789-2d3c1f3d-9712-43c7-91d5-123f0e8b3e43.png">
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/35408641/197097799-0f82deb8-9707-4d17-af90-2163131df8bf.png">
https://github.com/Megvii-BaseDetection/BEVDepth/blob/aaeee14923e8fc07b7c503349ace6b28efe42851/scripts/gen_info.py#L132
<img width="683" alt="image" src="https://user-images.githubusercontent.com/35408641/197097862-3474292a-f312-41cc-a3b6-14da6f061f9b.png">

**Comment by Barcelona16** [comment]
I had the same problem.

**Comment by yinchimaoliang** [comment]
Hi! Thanks for your contribution, I will fix this.
