### ISSUE TITLE
Visualization code

### ISSUE THREAD

**Issue by NorthSummer** [Megvii-BaseDetection/BEVDepth#90]
Are there any codes for visualizing the prediction results?  Many Thanks

**Comment by yinchimaoliang** [comment]
Hi, the script is provided.

**Comment by zhangjinsong3** [comment]
> Hi, the script is provided.

@yinchimaoliang  hello yinchimaoliang, I ran the visualization code and got the result like bellow. It seems the nms is not good enough to suppress all the redundant bboxes. Is this reasonable phenomenon?
![result](https://user-images.githubusercontent.com/14243638/197684266-dc776fbf-884b-4a01-ba08-32c64980fb4f.jpg)

**Comment by yinchimaoliang** [comment]
Hello @zhangjinsong3 . From the visualization result you provided, I believe it is reasonable. As for the nms problem, it is affected by the hyper parameter you set.

**Comment by ClaireMei** [comment]
I met the same problem and changed the nms_thr of test_cfg from 0.2(default) to 0.1, but the result figure has not changed. Could you please provide the best nms_thr and test_score_thr on the nuScenes valset or testset? Thx

**Comment by ClaireMei** [comment]
> > Hi, the script is provided.
> 
> @yinchimaoliang hello yinchimaoliang, I ran the visualization code and got the result like bellow. It seems the nms is not good enough to suppress all the redundant bboxes. Is this reasonable phenomenon? ![result](https://user-images.githubusercontent.com/14243638/197684266-dc776fbf-884b-4a01-ba08-32c64980fb4f.jpg)

Hi, have you solved the problem? Do you know which code to change?

**Comment by yinchimaoliang** [comment]
You can set the score threshold and give it a try,
